version: '2'

networks:
  default:
    driver: bridge

services:

  prometheus:
    build: images/prometheus
    depends_on:
      - dataproducer
    links:
      - dataproducer
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - './config/prometheus.yml:/etc/prometheus/prometheus.yml'

  dataproducer:
    build: images/dataproducer
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - '/var/lib/dataproducer:/var/lib/dataproducer'

  client:
    build: images/client
    restart: always
    links:
      - dataproducer

  grafana:
    build: images/grafana
    depends_on:
      - prometheus
    links:
      - prometheus
    ports:
      - '3000:3000'
    restart: always
